# Generated by Django 4.2.3 on 2023-07-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mytemplateweb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="templates/files"),
        ),
    ]
