# Generated by Django 4.2.3 on 2023-07-22 12:17

from django.db import migrations, models
import mytemplateweb.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mytemplateweb",
            "0004_remove_userprofile_email_remove_userprofile_password_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=mytemplateweb.models.user_profile_picture_path,
            ),
        ),
    ]
