# Generated by Django 4.2.3 on 2023-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mytemplateweb", "0005_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="", max_length=100, unique=True),
        ),
    ]
